name: Build & SLSA Provenance

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restaurer les packages NuGet
        run: nuget restore "Projet Pharmacie.sln"

      - name: Compiler le projet
        run: msbuild "Projet Pharmacie.sln" /p:Configuration=Release

      - name: Afficher les fichiers générés
        shell: powershell
        run: Get-ChildItem -Recurse -Filter "*.exe" | Select-Object FullName

      - name: Installer CycloneDX
        run: dotnet tool install --global CycloneDX

      - name: Générer le SBOM
        run: dotnet CycloneDX "Projet Pharmacie.csproj" -o ./sbom

      - name: Trouver le fichier SBOM généré
        shell: powershell
        run: Get-ChildItem -Recurse -Filter "bom.*" | Select-Object FullName

      - name: Uploader le SBOM
        uses: actions/upload-artifact@v4
        with:
          name: SBOM
          path: ./sbom/bom.json

      - name: Générer l'attestation SLSA
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "bin/Release/Projet Pharmacie.exe"
